version: "3.7"
services:
 api:
    build:
      context: ./
    restart: on-failure
    ports:
      - $APP_PORT:3000
    env_file:
      - ./.env.docker
    entrypoint: [/bin/sh]
    command:
      - -c
      - /app/xkcd api
